language: python

python:
  - 3.8

services:
  postgresql
addons:
  postgresql: '9.5'

install:
  - pip install -r requirements-dev.txt
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - flake8
  - pytest --cov=pypro

after_success:
  - codecov
